// Shot Specialty Cafe — menu data snapshot, taken from the live Foodics menu on 2026-08-31.
// Update this file by hand whenever the real menu changes.
const MENU_DATA = [
  {
    id: "new",
    name: "New On The Menu",
    nameAr: "الجديد في القائمة",
    icon: null,
    isNewBadge: true,
    items: [
      { name: "Dirty Espresso", nameAr: "إسبريسو ديرتي", desc: "Rich espresso blended with creamy Oatly milk, topped with smooth whipped cream and a sprinkle of cocoa powder.", descAr: "إسبريسو غني ممزوج بحليب أوتلي الكريمي، مغطى بكريمة مخفوقة ناعمة ورشة من مسحوق الكاكاو.", price: 28, img: "https://cdn.getsolo.io/17817880896a33edb925720_WhatsApp%20Image%202026-06-18%20at%205.01.32%20PM.jpeg" },
      { name: "Vanilla Brown Butter Oat Latte", nameAr: "لاتيه الزبدة البنية والفانيليا بالشوفان", desc: "Nutty brown butter, smooth vanilla, and creamy oatly come together with bold espresso for a rich and velvety latte.", descAr: "زبدة بنية غنية بالمكسرات، فانيليا ناعمة، وحليب الشوفان الكريمي يمتزج مع الإسبريسو القوي ليمنحك لاتيه غنياً ومخملياً.", price: 30, img: "https://cdn.getsolo.io/17854410346a6bab0a6954e_WhatsApp%20Image%202026-07-24%20at%201.50.48%20PM%20(2).jpeg" },
      { name: "Banana Pudding Latte", nameAr: "لاتيه بودينغ الموز", desc: "A creamy espresso latte inspired by our signature banana pudding dessert.", descAr: "لاتيه إسبريسو كريمي مستوحى من حلوى بودينغ الموز المميزة لدينا.", price: 30, img: "https://cdn.getsolo.io/17854406966a6ba9b863b8c_WhatsApp%20Image%202026-07-24%20at%201.50.48%20PM%20(1).jpeg" },
      { name: "Dirty Matcha Latte", nameAr: "لاتيه ماتشا ديرتي", desc: "Made with ceremonial matcha with bold cold brew.", descAr: "مصنوع من الماتشا الطقسية مع كولد برو قوي.", price: 30, img: "https://cdn.getsolo.io/17854404576a6ba8c917e4e_WhatsApp%20Image%202026-07-24%20at%201.50.48%20PM.jpeg" },
      { name: "Cowboy Sandwich", nameAr: "ساندويتش كاوبوي", desc: "A hearty chicken sandwich with fresh salad vegetables, chives, and our signature Cowboy sauce, served on a soft toasted bun.", descAr: "ساندويتش دجاج شهي مع خضروات السلطة الطازجة، الثوم المعمر، وصلصة الكاوبوي المميزة، يُقدم على خبز طري محمص.", price: 45, img: "https://cdn.getsolo.io/17854416306a6bad5e1f04b_Screenshot%202026-07-31%20000008.png" },
      { name: "Bresaola Sandwich", nameAr: "ساندويتش بريزاولا", desc: "A classic Italian-inspired sandwich featuring premium quality bresaola beef, creamy buffalo mozzarella, fresh rocca leaves, and sundried tomato pesto sauce, served on freshly baked ciabatta bread.", descAr: "ساندويتش مستوحى من المطبخ الإيطالي الكلاسيكي، يحتوي على لحم بريزاولا عالي الجودة، جبنة موزاريلا البوفالو الكريمية، أوراق الروكا الطازجة، وصلصة البيستو بالطماطم المجففة، يُقدم على خبز الشياباتا الطازج.", price: 50, img: "https://cdn.getsolo.io/17854421456a6baf6116e1c_Screenshot%202026-07-31%20000835.png" },
      { name: "Chicken Salad Sandwich", nameAr: "ساندويتش سلطة الدجاج", desc: "A classic chicken salad sandwich with tender chicken breast, crisp vegetables, fresh lollo rosso, and pickled cucumber on soft sliced bread.", descAr: "ساندويتش سلطة دجاج كلاسيكي مع صدر دجاج طري، خضروات مقرمشة، خس لولو روزا طازج، وخيار مخلل على خبز طري شرائح.", price: 42, img: null },
    ],
  },
  {
    id: "coffee-creation",
    name: "Coffee Creation",
    nameAr: "إبداعات القهوة",
    icon: "https://cdn.getsolo.io/176118500568f98ced14d95_1.png",
    items: [
      { name: "Espresso", nameAr: "إسبريسو", desc: "Freshly brewed espresso.", descAr: "إسبريسو طازج التحضير.", price: 19, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963562_9c282c53-3265-4187-aa89-8fa3a8b24a6f.jpg" },
      { name: "Americano", nameAr: "أمريكانو", desc: "Freshly brewed espresso and hot water.", descAr: "إسبريسو طازج مع ماء ساخن.", price: 19, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1722413184_9ca70e99-92e4-44a5-9df7-50c4ec0bad63.jpg" },
      { name: "Flat White", nameAr: "فلات وايت", desc: "Double shot of espresso with steamed milk and a thin layer of velvety micro foam.", descAr: "جرعة مزدوجة من الإسبريسو مع حليب مبخر وطبقة رقيقة من الرغوة المخملية.", price: 26, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963547_9c282c3b-3ddc-4ab9-a3bb-42041ec477a9.jpg" },
      { name: "Piccolo", nameAr: "بيكولو", desc: "Concentrated espresso shot and a small amount of steamed milk topped with a light layer of micro foam.", descAr: "جرعة إسبريسو مركزة مع كمية قليلة من الحليب المبخر مغطاة بطبقة خفيفة من الرغوة الدقيقة.", price: 24, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963660_9c282ce9-012e-4b25-951e-b41c15e0f70c.jpg" },
      { name: "Piccolo Rahash", nameAr: "بيكولو رهش", desc: "Bold ristretto shot, steamed milk, and topped with a light layer of micro foam and our signature rahash.", descAr: "جرعة ريستريتو قوية، حليب مبخر، ومغطاة بطبقة خفيفة من الرغوة الدقيقة ورهشنا المميز.", price: 26, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716969018_9c284cd7-75d4-4990-aa3c-3f2a8bb99334.jpg" },
      { name: "SPC Rahash", nameAr: "إس بي سي رهش", desc: "Blend of espresso, milk, and sweetened condensed milk, served over ice with our signature rahash.", descAr: "مزيج من الإسبريسو والحليب والحليب المكثف المحلى، يُقدم مثلجاً مع رهشنا المميز.", price: 31, img: "https://cdn.getsolo.io/177262137769a80e41a3f18_SPC%20Rahash.png" },
      { name: "Cortado", nameAr: "كورتادو", desc: "Shot of espresso and an equal amount of steamed milk.", descAr: "جرعة إسبريسو مع كمية مساوية من الحليب المبخر.", price: 24, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963527_9c282c1c-cde4-4734-875d-9f89976182d8.jpg" },
      { name: "Rahash Latte", nameAr: "لاتيه رهش", desc: "Blend of espresso, steamed milk, with our signature rahash.", descAr: "مزيج من الإسبريسو والحليب المبخر مع رهشنا المميز.", price: 31, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716969103_9c284d5a-3d3d-4c21-a59d-3af7856491a6.jpg" },
      { name: "SPH Rahash", nameAr: "إس بي إتش رهش", desc: "Blend of espresso, steamed milk, and sweetened condensed milk, with our signature rahash.", descAr: "مزيج من الإسبريسو والحليب المبخر والحليب المكثف المحلى مع رهشنا المميز.", price: 31, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716968989_9c284cab-27d4-4a3e-a328-cb0682b372af.jpg" },
      { name: "Spanish Latte", nameAr: "لاتيه إسباني", desc: "Blend of espresso, milk, and sweetened condensed milk.", descAr: "مزيج من الإسبريسو والحليب والحليب المكثف المحلى.", price: 30, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963642_9c282ccd-4a16-4f77-a710-1474692539b8.jpg" },
      { name: "Latte", nameAr: "لاتيه", desc: "Shot of espresso combined with steamed milk and topped with a light layer of micro foam.", descAr: "جرعة إسبريسو ممزوجة بالحليب المبخر ومغطاة بطبقة خفيفة من الرغوة الدقيقة.", price: 26, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963616_9c282ca4-93ba-4363-8980-d5a83ab4e0e4.jpg" },
      { name: "Cappuccino", nameAr: "كابتشينو", desc: "Shot of espresso, steamed milk, and a thick layer of milk foam.", descAr: "جرعة إسبريسو، حليب مبخر، وطبقة سميكة من رغوة الحليب.", price: 26, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963595_9c282c85-36c9-4770-9a6f-fac4118ffd13.jpg" },
      { name: "Affogato", nameAr: "أفوغاتو", desc: "Made with a scoop of ice cream topped with a shot of hot espresso.", descAr: "مصنوع من كرة آيس كريم مغطاة بجرعة إسبريسو ساخنة.", price: 28, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716963579_9c282c6c-0b07-4341-bf54-f0b78da14539.jpg" },
      { name: "Iced Spanish Latte", nameAr: "لاتيه إسباني مثلج", desc: "Blend of espresso, milk, and sweetened condensed milk, served with ice.", descAr: "مزيج من الإسبريسو والحليب والحليب المكثف المحلى، يُقدم مع الثلج.", price: 30, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716970802_9c285779-972a-4d20-9f87-a2f3920077b7.jpg" },
      { name: "Shot Shake", nameAr: "شوت شيك", desc: "A concentrated and energizing shake served in a shot sized portion.", descAr: "مشروب مركز ومنعش يُقدم بحجم الشوت.", price: 30, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716970776_9c285752-4294-47ff-bb96-700345def30e.jpg" },
    ],
  },
  {
    id: "filtered-coffee",
    name: "Filtered Coffee",
    nameAr: "القهوة المفلترة",
    icon: "https://cdn.getsolo.io/176699751069523e06586fd_V60%20(512x512).png",
    items: [
      { name: "Kalita Waves", nameAr: "كاليتا ويفز", desc: "Kalita Wave is a flat-bottom pour-over brewing method that delivers a clean, balanced cup with even extraction. Known for its consistency and smooth flavor profile, it's ideal for showcasing specialty coffee without bitterness.", descAr: "كاليتا ويف هي طريقة تحضير بالتقطير ذات قاع مسطح توفر كوباً نظيفاً ومتوازناً باستخلاص متساوٍ. معروفة بثباتها ونكهتها الناعمة، وهي مثالية لإبراز قهوة مختصة دون مرارة.", price: 32, img: "https://cdn.getsolo.io/17694059256976fde588564_Kalita%20Waves.png" },
      { name: "V60 Iced Shaken", nameAr: "في60 مثلج مخفوق", desc: "Expertly brewed and shaken to perfection, a refined, foamy pour-over with a clean, elegant finish.", descAr: "محضّرة ومخفوقة بإتقان، تقطير راقٍ ورغوي بلمسة نهائية نظيفة وأنيقة.", price: 40, img: "https://cdn.getsolo.io/176699757469523e465b0c6_Iced%20Shaken%20V60%20(512x512).png" },
      { name: "V60", nameAr: "في60", desc: "A pour-over coffee brewed, showcasing the rich flavors and aromas of freshly ground coffee.", descAr: "قهوة مقطّرة تُبرز النكهات والروائح الغنية للقهوة المطحونة طازجاً.", price: 32, img: "https://cdn.getsolo.io/176699749269523df445792_V60%20(512x512).png" },
      { name: "Cold Brew", nameAr: "كولد برو", desc: "Made with the finest quality coffee beans, expertly brewed to perfection, and served over ice will awaken your senses and delight your taste buds!", descAr: "مصنوعة من أجود حبوب القهوة، مقطّرة بإتقان، وتُقدم على الثلج لتوقظ حواسك وتُبهج ذوقك!", price: 32, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716970937_9c285848-d5aa-4fd3-b541-ed7550c74240.jpg" },
    ],
  },
  {
    id: "matcha",
    name: "Matcha",
    nameAr: "ماتشا",
    icon: "https://cdn.getsolo.io/176118623068f991b6821f2_Matcha.png",
    items: [
      { name: "Matcha Latte", nameAr: "لاتيه ماتشا", desc: "Made with high-quality matcha powder and milk.", descAr: "مصنوع من مسحوق الماتشا عالي الجودة والحليب.", price: 30, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716969142_9c284d94-bdeb-4b99-9d93-29f38e7b3e60.jpg" },
      { name: "Iced Matcha Latte", nameAr: "لاتيه ماتشا مثلج", desc: "Made with high-quality matcha powder and milk, served with ice.", descAr: "مصنوع من مسحوق الماتشا عالي الجودة والحليب، يُقدم مع الثلج.", price: 32, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1732601311_9d944491-8c22-4109-994b-ad35ea815cf8.png" },
      { name: "Salted Vanilla Matcha", nameAr: "ماتشا الفانيليا المملحة", desc: "Made with high-quality matcha powder, milk, and salted vanilla syrup, served with ice.", descAr: "مصنوعة من مسحوق الماتشا عالي الجودة، الحليب، وشراب الفانيليا المملح، تُقدم مع الثلج.", price: 37, img: "https://cdn.getsolo.io/177322655069b14a362eea8_Salted%20Vanilla.jpg" },
      { name: "Strawberry Matcha", nameAr: "ماتشا الفراولة", desc: "Made with high-quality matcha powder, milk, and strawberry syrup, served with ice.", descAr: "مصنوعة من مسحوق الماتشا عالي الجودة، الحليب، وشراب الفراولة، تُقدم مع الثلج.", price: 35, img: "https://cdn.getsolo.io/1771574051699813231728d_Strawberry%20Matcha.png" },
      { name: "Coconut Matcha Cloud", nameAr: "سحابة ماتشا جوز الهند", desc: "A refreshing coconut water topped with creamy matcha cloud.", descAr: "ماء جوز الهند المنعش مغطى بسحابة ماتشا كريمية.", price: 40, img: "https://cdn.getsolo.io/17803788866a1e6d06c3b8c_SHOT%207.jpg" },
    ],
  },
  {
    id: "chocolates",
    name: "Chocolates",
    nameAr: "الشوكولاتة",
    icon: "https://cdn.getsolo.io/17802731066a1ccfd2ada5c_Hot_Chocolate__1__menu.jpg",
    items: [
      { name: "Hot Chocolate", nameAr: "شوكولاتة ساخنة", desc: "Our signature hot chocolate topped with smooth salted vanilla cream.", descAr: "شوكولاتتنا الساخنة المميزة مغطاة بكريمة الفانيليا المملحة الناعمة.", price: 35, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1732609492_9d947555-f8ad-4fe5-aafd-38345c66bfd1.png" },
      { name: "Iced Chocolate", nameAr: "شوكولاتة مثلجة", desc: "Our signature iced chocolate topped with smooth salted vanilla cream.", descAr: "شوكولاتتنا المثلجة المميزة مغطاة بكريمة الفانيليا المملحة الناعمة.", price: 35, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1732533843_9d92b26e-444c-4d92-9f38-a8f4bd114304.png" },
    ],
  },
  {
    id: "milkshakes",
    name: "Milkshakes",
    nameAr: "ميلك شيك",
    icon: "https://cdn.getsolo.io/177261969369a807adb27d3_Nutella%20Milkshake.png",
    items: [
      { name: "Nutella Milkshake", nameAr: "ميلك شيك نوتيلا", desc: "Made with milk, vanilla ice cream, and nutella sauce.", descAr: "مصنوع من الحليب، آيس كريم الفانيليا، وصلصة نوتيلا.", price: 37, img: "https://cdn.getsolo.io/177261953569a8070f0d3a7_Nutella%20Milkshake.png" },
      { name: "Oreo Milkshake", nameAr: "ميلك شيك أوريو", desc: "Made with milk, vanilla ice cream, and crushed oreo cookies.", descAr: "مصنوع من الحليب، آيس كريم الفانيليا، وبسكويت أوريو المطحون.", price: 39, img: "https://cdn.getsolo.io/177261955869a807263ae99_Oreo%20Milkshake.png" },
      { name: "Vanilla Milkshake", nameAr: "ميلك شيك فانيليا", desc: "Made with milk and rich vanilla ice cream.", descAr: "مصنوع من الحليب وآيس كريم الفانيليا الغني.", price: 37, img: "https://cdn.getsolo.io/177261955169a8071fe65c4_Vanilla%20Milkshake.png" },
      { name: "Espresso Milkshake", nameAr: "ميلك شيك إسبريسو", desc: "Made with milk, vanilla ice cream, and espresso.", descAr: "مصنوع من الحليب، آيس كريم الفانيليا، والإسبريسو.", price: 38, img: "https://cdn.getsolo.io/177261956569a8072d29ab2_Espresso%20Milkshake.png" },
    ],
  },
  {
    id: "mocktails",
    name: "Mocktails",
    nameAr: "موكتيلز",
    icon: "https://cdn.getsolo.io/17854437356a6bb5975e342_16.jpg",
    items: [
      { name: "Classic Mojito", nameAr: "موهيتو كلاسيكي", desc: "A refreshing mocktail crafted with muddled mint, fresh lime, and sparkling soda.", descAr: "موكتيل منعش مصنوع من النعناع المهروس، الليمون الطازج، والصودا الفوارة.", price: 35, img: "https://cdn.getsolo.io/17854433676a6bb4273859b_17.jpg" },
      { name: "Peach Bellini", nameAr: "بيليني الخوخ", desc: "Made with sparkling peach water and peach purée syrup, garnished with a dehydrated peach slice.", descAr: "مصنوع من ماء الخوخ الفوار وشراب هريس الخوخ، مزين بشريحة خوخ مجففة.", price: 35, img: "https://cdn.getsolo.io/17802718326a1ccad87ace1_SHOT%208.jpg" },
    ],
  },
  {
    id: "tea-selection",
    name: "Tea Selection",
    nameAr: "تشكيلة الشاي",
    icon: "https://cdn.getsolo.io/1762154684690858bcc3ac3_Tea%20Selection.jpg",
    items: [
      { name: "English Breakfast", nameAr: "إنجليش بريكفاست", desc: "A bold, full-bodied black tea with smooth malty notes, timeless, refined, and perfect any time of day.", descAr: "شاي أسود جريء وممتلئ القوام بنكهات شعيرية ناعمة، خالد وراقٍ ومثالي في أي وقت من اليوم.", price: 21, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716998333_9c28fb93-8075-47fe-92da-acfe757060fd.jpg" },
      { name: "Chamomile", nameAr: "بابونج", desc: "A delicate floral infusion, soothing and gentle on the senses. Naturally calming and known to aid restful sleep and ease digestion.", descAr: "منقوع زهري لطيف، مهدئ ولطيف على الحواس. يُعرف طبيعياً بمساعدته على النوم الهادئ وتسهيل الهضم.", price: 21, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716998206_9c28fad1-a9e4-45a7-a5e0-730a5a4eeb14.jpg" },
    ],
  },
  {
    id: "acai",
    name: "Acai",
    nameAr: "أساي",
    icon: "https://cdn.getsolo.io/176118620968f991a1ccf9f_20.jpg",
    items: [
      { name: "Acai Bowl", nameAr: "وعاء أساي", desc: "Enjoy a refreshing and healthy acai bowl. Mix and match your favorite toppings to create your perfect bowl.", descAr: "استمتع بوعاء أساي منعش وصحي. امزج وطابق إضافاتك المفضلة لتحصل على وعائك المثالي.", price: 48, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716974401_9c286cee-427f-4c9c-a7e5-6f8bcba77525.jpg" },
      { name: "Acai Smoothie", nameAr: "سموذي أساي", desc: "Smooth blend of acai, oat milk and your favorite toppings.", descAr: "مزيج ناعم من الأساي وحليب الشوفان وإضافاتك المفضلة.", price: 42, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716972504_9c28619f-9ebb-4325-bfd0-3c7bfbec04c5.jpg" },
      { name: "Acai Peanut Butter Smoothie", nameAr: "سموذي أساي بزبدة الفول السوداني", desc: "A nutritious and flavorful smoothie made with Acai, mixed berries, peanut butter and coconut water.", descAr: "سموذي مغذٍ وغني بالنكهة مصنوع من الأساي والتوت المشكل وزبدة الفول السوداني وماء جوز الهند.", price: 43, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716972375_9c2860d9-d3bb-43aa-86d4-aff4550b0691.jpg" },
    ],
  },
  {
    id: "all-day-bites",
    name: "All Day Bites",
    nameAr: "وجبات طوال اليوم",
    icon: "https://cdn.getsolo.io/177806961669fb30701e9fd_Egg%20&%20Chips%20Breakfast%20Bun%20.png",
    items: [
      { name: "Egg & Chips Breakfast Bun", nameAr: "صمونة الإفطار بالبيض والشيبس", desc: "Brioche bun with spicy mayo, scrambled eggs mixed with herbs, and a side of Omani chips.", descAr: "صمونة بريوش مع مايونيز حار، بيض مخفوق ممزوج بالأعشاب، وطبق جانبي من الشيبس العماني.", price: 37, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1726836288_9d0e0a5b-6971-4143-be78-bca5349dc517.png" },
      { name: "Beef Bacon Egg Bun", nameAr: "صمونة البيض ولحم البيكون البقري", desc: "Smoky beef bacon layered in soft brioche bun with savory touch. Simple, flavorful and made to satisfy.", descAr: "لحم بيكون بقري مدخن بين طبقات صمونة بريوش طرية بلمسة شهية. بسيط، غني بالنكهة، ومُشبع.", price: 41, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1747622602_9ef20271-c1c5-45e5-8fb8-73d4f385f074.png" },
      { name: "Truffle Mushroom and Egg Bun", nameAr: "صمونة الفطر بالكمأة والبيض", desc: "A creamy truffle mushroom mix tucked in a soft, buttery brioche bun. Rich, comforting, and full of flavor in every bite.", descAr: "مزيج كريمي من فطر الكمأة داخل صمونة بريوش طرية وزبدية. غنية، مريحة، ومليئة بالنكهة في كل قضمة.", price: 39, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1747622616_9ef20286-e396-40a3-abf6-5902c47318cf.png" },
      { name: "Cheesy Omelette Croissant", nameAr: "كرواسون الأومليت بالجبن", desc: "A buttery croissant omelette with a perfect blend of parmesan and cheddar cheese.", descAr: "كرواسون زبدي بأومليت بمزيج مثالي من جبنة البارميزان والشيدر.", price: 36, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1757904443_9fe166fc-ce6f-4076-90ea-65a90ab944f6.png" },
      { name: "Croissant Plain", nameAr: "كرواسون سادة", desc: "Made with layers of flaky, buttery pastry dough, the croissant has a light and delicate texture that is perfect for breakfast or as a snack.", descAr: "مصنوع من طبقات رقيقة وزبدية من عجينة الفطائر، له قوام خفيف ورقيق مثالي للإفطار أو كوجبة خفيفة.", price: 16, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716999650_9c29036c-032f-4b53-9543-54d7db28580c.jpg" },
      { name: "Croissant Cheese", nameAr: "كرواسون بالجبن", desc: "A flaky, buttery croissant filled with cheese, offering a delightful combination of savory and rich flavors in every bite.", descAr: "كرواسون رقيق وزبدي محشو بالجبن، يقدم مزيجاً رائعاً من النكهات المالحة والغنية في كل قضمة.", price: 25, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716999676_9c290393-cc4a-4826-adcb-b5fd57187df2.jpg" },
      { name: "Croissant Kiri and Honey", nameAr: "كرواسون كيري والعسل", desc: "A croissant filled with creamy Kiri cheese and drizzled with sweet honey.", descAr: "كرواسون محشو بجبنة كيري الكريمية ومزين بالعسل الحلو.", price: 25, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1716998602_9c28fd2d-6e35-4fdf-901e-2c55c0b2ba34.jpg" },
    ],
  },
  {
    id: "sandwiches-wraps",
    name: "Sandwiches & Wraps",
    nameAr: "ساندويتشات ولفائف",
    icon: "https://cdn.getsolo.io/17854429206a6bb268ce213_SHOT%20Clubhouse.jpg",
    items: [
      { name: "SHOT Club Sandwich", nameAr: "ساندويتش شوت كلوب", desc: "White bread layered with cheddar cheese, smoked turkey breast, beef bacon, pickled cucumber, and lettuce, served with chips.", descAr: "خبز أبيض بطبقات من جبنة الشيدر، صدر ديك رومي مدخن، لحم بيكون بقري، خيار مخلل، وخس، يُقدم مع الشيبس.", price: 45, img: "https://cdn.getsolo.io/177770367669f59afcef323_14.jpg" },
      { name: "Chicken Wrap", nameAr: "لفافة الدجاج", desc: "This features a crispy breaded chicken breast with a touch of spice, fresh lettuce, and a flavorful sauce wrapped in a soft tortilla.", descAr: "صدر دجاج مقرمش ومقلي بلمسة من التوابل، خس طازج، وصلصة شهية، ملفوفة في تورتيلا طرية.", price: 29, img: "https://cdn.getsolo.io/176701326869527b94cb0fb_Chicken%20Wrap.jpg" },
      { name: "Tuna Melt", nameAr: "تونة ميلت", desc: "Tuna melt sandwich with flavorful tuna mix and creamy cheese.", descAr: "ساندويتش تونة ميلت مع مزيج تونة شهي وجبنة كريمية.", price: 38, img: "https://cdn.getsolo.io/1769603383697a0137d9ddb_Tuna%20Melt.jpg" },
      { name: "Halloumi and Sundried Tomato Sandwich", nameAr: "ساندويتش الحلوم والطماطم المجففة", desc: "Grilled Halloumi, sundried tomato, baby rocca, balsamic glaze, zaatar powder, labneh and your choice of bread (Focaccia or Brown Rye Bread).", descAr: "حلوم مشوي، طماطم مجففة، روكا صغيرة، صلصة البلسميك، بهارات الزعتر، لبنة، واختيارك من الخبز (فوكاتشيا أو خبز الجاودار البني).", price: 38, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1760684592_a02221f7-b7d1-4bc6-bfed-44d4f7f9a896.png" },
      { name: "Roast Beef", nameAr: "روست بيف", desc: "Savory roast beef sandwich featuring tender prime roast beef, caramelized onions, balsamic glaze, Rocca leaves, and a kick of spicy mayo.", descAr: "ساندويتش لحم بقري مشوي شهي يحتوي على لحم بقري مشوي فاخر، بصل مكرمل، صلصة البلسميك، أوراق الروكا، ولمسة من المايونيز الحار.", price: 39, img: "https://cdn.getsolo.io/1769603439697a016f09dc2_Roast%20Beef%20(2).jpg" },
      { name: "Smoked Turkey", nameAr: "ديك رومي مدخن", desc: "Smoked Turkey sandwich with tender smoked turkey slices, Emmental cheese, and fresh baby gem lettuce.", descAr: "ساندويتش الديك الرومي المدخن مع شرائح ديك رومي مدخن طرية، جبنة إيمنتال، وخس بيبي جيم طازج.", price: 38, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1752650186_9f67112d-f376-42dc-8f6e-49f312b46fe8.png" },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    nameAr: "الحلويات",
    icon: "https://cdn.getsolo.io/177261903969a8051fb256a_Screenshot%202026-03-04%20140637.png",
    items: [
      { name: "Crepe Nutella", nameAr: "كريب نوتيلا", desc: "Crepe with rich nutella sauce.", descAr: "كريب مع صلصة نوتيلا الغنية.", price: 37, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1717001329_9c290d6f-373d-493b-9ee6-db24515913f6.jpg" },
      { name: "Banana Pudding", nameAr: "بودينغ الموز", desc: "Creamy vanilla custard layered with fresh bananas and biscuit layers.", descAr: "كاسترد فانيليا كريمي بطبقات من الموز الطازج والبسكويت.", price: 33, img: "https://cdn.getsolo.io/177261882269a80446205d5_Screenshot%202026-03-04%20140637.png" },
      { name: "Brownies", nameAr: "براوني", desc: "Indulge in the richness of our fudgy Brownies, made with chocolate and butter for intense flavor and finished with a crackly top for ultimate indulgence.", descAr: "استمتع بغنى البراوني الطري المصنوع من الشوكولاتة والزبدة لنكهة مكثفة، مع طبقة علوية مقرمشة لمتعة كاملة.", price: 16, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1717002932_9c2916fd-251e-4b58-b5d8-c7927ab356c4.jpeg" },
      { name: "Salted Brownie Melted", nameAr: "براوني مملح ذائب", desc: "A mouthwatering brownie with a layer of salted goodness.", descAr: "براوني شهي بطبقة من النكهة المملحة.", price: 30, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1717001809_9c29104b-7710-42dd-b36f-dfe6688d1b16.jpg" },
      { name: "Chocolate Chip Cookies", nameAr: "كوكيز رقائق الشوكولاتة", desc: "Irresistibly soft chocolate chip cookies with a perfect balance of chewy texture and melted chocolate chunks.", descAr: "كوكيز طرية ولا تُقاوم برقائق الشوكولاتة مع توازن مثالي بين القوام الطري وقطع الشوكولاتة الذائبة.", price: 15, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1724137550_9ccf349f-74a7-4b91-a5df-47c313f53cfc.jpg" },
      { name: "S'mores Cookies", nameAr: "كوكيز سموريز", desc: "Classic campfire style cookies with chocolate and marshmallow.", descAr: "كوكيز كلاسيكية بنكهة نار المخيم مع الشوكولاتة والمارشميلو.", price: 15, img: "https://cdn.getsolo.io/17695199976978bb7d8ac7d_S'mores%20Cookies.png" },
      { name: "Chocolate Nutella Cookies", nameAr: "كوكيز الشوكولاتة والنوتيلا", desc: "Decadent cookies featuring Nutella spread, baked to perfection with a soft center and crisp edges.", descAr: "كوكيز فاخرة بحشوة نوتيلا، مخبوزة بإتقان بمركز طري وأطراف مقرمشة.", price: 15, img: "https://cdn.getsolo.io/17695198816978bb098ac8b_Chocolate%20Nutella.png" },
      { name: "Chocolate Kinder Cake", nameAr: "كيك الشوكولاتة كيندر", desc: "Moist Chocolate Kinder Cake with chocolate ganache, topped with crunchy corn flakes and kinder speculoos sauce.", descAr: "كيك شوكولاتة كيندر رطب مع صلصة الغاناش، مزين برقائق الذرة المقرمشة وصلصة كيندر سبيكولوس.", price: 35, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1718082160_9c4237b0-44d3-4f5a-8d24-62f518b96aee.jpg" },
      { name: "Vanilla Soft Cheesecake", nameAr: "تشيز كيك الفانيليا الطرية", desc: "Our homemade version of vanilla soft cheese cake, it's delicious, with a burnt top and a rich, creamy interior.", descAr: "نسختنا المنزلية من تشيز كيك الفانيليا الطرية، لذيذة، بطبقة علوية محروقة قليلاً وقوام داخلي غني وكريمي.", price: 30, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1717002840_9c29166f-da93-4aac-876b-9da18448bbea.jpg" },
      { name: "Chocolate Soft Cheesecake", nameAr: "تشيز كيك الشوكولاتة الطرية", desc: "Our homemade version of Chocolate Soft Cheese Cake. It's delicious, with a burnt top and a rich, creamy interior. With Nutella sauce poured on top.", descAr: "نسختنا المنزلية من تشيز كيك الشوكولاتة الطرية. لذيذة، بطبقة علوية محروقة قليلاً وقوام داخلي غني وكريمي، مع صلصة نوتيلا مسكوبة عليها.", price: 36, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1717002887_9c2916b7-ba5b-478d-a5cb-43311cbd445a.jpg" },
      { name: "Honey Pudding Slice", nameAr: "شريحة بودينغ العسل", desc: "A slice of pudding infused with honey flavor.", descAr: "شريحة بودينغ منكهة بالعسل.", price: 39, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1717001776_9c291018-3297-449d-9c3d-98a6c5dfc091.jpg" },
      { name: "Pavlova", nameAr: "بافلوفا", desc: "A dessert featuring meringue.", descAr: "حلوى تتميز بالميرينغ.", price: 39, img: "https://foodics-console-production.s3.eu-west-1.amazonaws.com/images/398629_1717001990_9c29115f-c931-4bc6-8c06-bc11cea7476a.jpg" },
    ],
  },
];
